# Generated by Django 5.2.15 on 2026-06-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_master_name', models.CharField(blank=True, max_length=200)),
                ('cutting_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabric_type_quality', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=200)),
                ('job_card_no', models.CharField(max_length=100)),
                ('total_pcs', models.PositiveIntegerField()),
                ('total_colours', models.PositiveIntegerField()),
                ('total_weight_meter', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_per_pcs', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cutting Report',
                'verbose_name_plural': 'Cutting Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cutting_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.cuttingreport')),
            ],
        ),
        migrations.CreateModel(
            name='MasterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_card_number', models.CharField(max_length=100, verbose_name='Job Card Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Entry',
                'verbose_name_plural': 'Master Entries',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'job_card_number')},
            },
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='master_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_reports', to='core.masterentry'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'Person 2'), ('P3', 'Person 3'), ('P4', 'Person 4'), ('P5', 'Person 5'), ('P6', 'Person 6'), ('P7', 'Person 7'), ('P8', 'Person 8'), ('P9', 'Person 9'), ('P10', 'Person 10'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
