# Generated by Django 5.2.15 on 2026-06-15 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_master_name', models.CharField(blank=True, max_length=200)),
                ('cutting_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabric_type_quality', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=200)),
                ('job_card_no', models.CharField(max_length=100)),
                ('total_pcs', models.PositiveIntegerField()),
                ('total_colours', models.PositiveIntegerField()),
                ('total_weight_meter', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_per_pcs', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Person 2 Report',
                'verbose_name_plural': 'Person 2 Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person2ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person2_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person2_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person2report')),
            ],
        ),
    ]
