# Generated by Django 5.2.15 on 2026-06-15 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person2report_person2reportphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person2report',
            options={'ordering': ['-created_at'], 'verbose_name': 'CR Lakshay', 'verbose_name_plural': 'CR Lakshay'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Person 4'), ('P5', 'Person 5'), ('P6', 'Person 6'), ('P7', 'Person 7'), ('P8', 'Person 8'), ('P9', 'Person 9'), ('P10', 'Person 10'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.CreateModel(
            name='Person3Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_master_name', models.CharField(blank=True, max_length=200)),
                ('cutting_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabric_type_quality', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=200)),
                ('job_card_no', models.CharField(max_length=100)),
                ('total_pcs', models.PositiveIntegerField()),
                ('total_colours', models.PositiveIntegerField()),
                ('total_weight_meter', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_per_pcs', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person3_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'CR Rahul',
                'verbose_name_plural': 'CR Rahul',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person3ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person3_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person3_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person3report')),
            ],
        ),
    ]
