# Generated by Django 5.2.15 on 2026-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_person2report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person2report',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person3report',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
