# Generated by Django 5.2.15 on 2026-06-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuttingreport_signature_person2report_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person4Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=100)),
                ('line_in_date', models.DateField(blank=True, null=True)),
                ('total_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('line_out_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('darji_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('folding_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overlock_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('option_1', models.CharField(blank=True, max_length=200)),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person4_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Stitching Miya Ji',
                'verbose_name_plural': 'Stitching Miya Ji',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person4ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person4_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person4_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person4report')),
            ],
        ),
    ]
