# Generated by Django 5.2.15 on 2026-06-16 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_person4report_darji_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person5Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobworker', models.CharField(max_length=200)),
                ('job_work_type', models.CharField(choices=[('Job Work In', 'Job Work In'), ('Job work Out', 'Job work Out')], max_length=50)),
                ('purpose', models.CharField(max_length=300)),
                ('job_card_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('any_other_problem', models.TextField()),
                ('total_pcs_short', models.PositiveIntegerField()),
                ('total_pcs', models.PositiveIntegerField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person5_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Job Work',
                'verbose_name_plural': 'Job Work',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person5ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person5_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person5_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person5report')),
            ],
        ),
    ]
