# Generated by Django 5.2.15 on 2026-06-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person5report_person5reportphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person6Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lot_no', models.CharField(max_length=100)),
                ('total_pcs', models.PositiveIntegerField()),
                ('total_pcs_short', models.PositiveIntegerField()),
                ('total_pcs_packed', models.PositiveIntegerField()),
                ('green_tape', models.PositiveIntegerField()),
                ('red_tape', models.PositiveIntegerField()),
                ('blue_tape', models.PositiveIntegerField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person6_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Finishing Report',
                'verbose_name_plural': 'Finishing Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person6ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person6_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person6_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person6report')),
            ],
        ),
    ]
