# Generated by Django 5.2.15 on 2026-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person6report_person6reportphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person5reportphoto',
            name='person5_report',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Stitching Miya Ji'), ('P5', 'Job Work'), ('P6', 'Finishing Report'), ('P7', 'Person 7'), ('P8', 'Person 8'), ('P9', 'Person 9'), ('P10', 'Person 10'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.DeleteModel(
            name='Person4ReportPhoto',
        ),
        migrations.DeleteModel(
            name='Person5ReportPhoto',
        ),
    ]
