# Generated by Django 5.2.15 on 2026-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_person5reportphoto_person5_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='size_2xl',
            field=models.PositiveIntegerField(default=0, verbose_name='2XL'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_3xl',
            field=models.PositiveIntegerField(default=0, verbose_name='3XL'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_4xl',
            field=models.PositiveIntegerField(default=0, verbose_name='4XL'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_l',
            field=models.PositiveIntegerField(default=0, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_m',
            field=models.PositiveIntegerField(default=0, verbose_name='M'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_s',
            field=models.PositiveIntegerField(default=0, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='size_xl',
            field=models.PositiveIntegerField(default=0, verbose_name='XL'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_2xl',
            field=models.PositiveIntegerField(default=0, verbose_name='2XL'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_3xl',
            field=models.PositiveIntegerField(default=0, verbose_name='3XL'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_4xl',
            field=models.PositiveIntegerField(default=0, verbose_name='4XL'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_l',
            field=models.PositiveIntegerField(default=0, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_m',
            field=models.PositiveIntegerField(default=0, verbose_name='M'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_s',
            field=models.PositiveIntegerField(default=0, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='person2report',
            name='size_xl',
            field=models.PositiveIntegerField(default=0, verbose_name='XL'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_2xl',
            field=models.PositiveIntegerField(default=0, verbose_name='2XL'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_3xl',
            field=models.PositiveIntegerField(default=0, verbose_name='3XL'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_4xl',
            field=models.PositiveIntegerField(default=0, verbose_name='4XL'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_l',
            field=models.PositiveIntegerField(default=0, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_m',
            field=models.PositiveIntegerField(default=0, verbose_name='M'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_s',
            field=models.PositiveIntegerField(default=0, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='person3report',
            name='size_xl',
            field=models.PositiveIntegerField(default=0, verbose_name='XL'),
        ),
        migrations.AlterField(
            model_name='cuttingreport',
            name='total_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person2report',
            name='total_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person3report',
            name='total_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
