# Generated by Django 5.2.15 on 2026-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cuttingreport_size_2xl_cuttingreport_size_3xl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_excel_download_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
