# Generated by Django 5.2.15 on 2026-06-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person2reportphoto',
            name='person2_report',
        ),
        migrations.RemoveField(
            model_name='person3report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='person3report',
            name='cutting_report',
        ),
        migrations.RemoveField(
            model_name='person3reportphoto',
            name='person3_report',
        ),
        migrations.DeleteModel(
            name='Person2Report',
        ),
        migrations.DeleteModel(
            name='Person2ReportPhoto',
        ),
        migrations.DeleteModel(
            name='Person3Report',
        ),
        migrations.DeleteModel(
            name='Person3ReportPhoto',
        ),
    ]
