# Generated by Django 5.2.15 on 2026-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_person2reportphoto_person2_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='report_type',
            field=models.CharField(choices=[('P1', 'Cutting Master'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul')], default='P1', max_length=2),
        ),
    ]
