# Generated by Django 5.2.15 on 2026-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cuttingreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person6report',
            name='total_tape',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
