# Generated by Django 5.2.15 on 2026-06-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person6report_total_tape'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingReportColorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('size_s', models.PositiveIntegerField(default=0)),
                ('size_m', models.PositiveIntegerField(default=0)),
                ('size_l', models.PositiveIntegerField(default=0)),
                ('size_xl', models.PositiveIntegerField(default=0)),
                ('size_2xl', models.PositiveIntegerField(default=0)),
                ('size_3xl', models.PositiveIntegerField(default=0)),
                ('size_4xl', models.PositiveIntegerField(default=0)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_details', to='core.cuttingreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
