# Generated by Django 5.2.15 on 2026-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cuttingreportcolordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='unit',
            field=models.CharField(choices=[('Weight', 'Weight'), ('Meters', 'Meters')], default='Weight', max_length=10),
        ),
    ]
