# Generated by Django 5.2.15 on 2026-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cuttingreport_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreportcolordetail',
            name='total_weight_meter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cuttingreportcolordetail',
            name='unit',
            field=models.CharField(choices=[('Weight', 'Weight'), ('Meters', 'Meters')], default='Weight', max_length=10),
        ),
    ]
