# Generated by Django 5.2.15 on 2026-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cuttingreportcolordetail_total_weight_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingreportphoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='person6reportphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='cuttingreportphoto',
            name='photo_content_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
        migrations.AddField(
            model_name='cuttingreportphoto',
            name='photo_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingreportphoto',
            name='photo_name',
            field=models.CharField(default='photo.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='person6reportphoto',
            name='photo_content_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
        migrations.AddField(
            model_name='person6reportphoto',
            name='photo_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person6reportphoto',
            name='photo_name',
            field=models.CharField(default='photo.jpg', max_length=255),
        ),
    ]
