# Generated by Django 5.2.15 on 2026-06-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cuttingreportphoto_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingreport',
            name='total_weight_meter',
        ),
        migrations.RemoveField(
            model_name='cuttingreport',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='cuttingreportcolordetail',
            name='total_weight_meter',
        ),
        migrations.RemoveField(
            model_name='cuttingreportcolordetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='total_meters',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuttingreportcolordetail',
            name='total_meters',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuttingreportcolordetail',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
