# Generated by Django 5.2.15 on 2026-06-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cuttingreport_total_weight_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person4report',
            name='line_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Person4ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person4_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.person4report')),
            ],
        ),
    ]
