# Generated by Django 5.2.15 on 2026-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_person4report_line_out_date_person4reportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='person4report',
            name='signature_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person5report',
            name='signature_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
