# Generated by Django 5.2.15 on 2026-06-23 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_person4report_signature_2_person5report_signature_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('requires_cutting', models.BooleanField(default=False)),
                ('requires_jobwork', models.BooleanField(default=False)),
                ('requires_stitching', models.BooleanField(default=False)),
                ('requires_finishing', models.BooleanField(default=False)),
                ('is_cutting_done', models.BooleanField(default=False)),
                ('is_jobwork_done', models.BooleanField(default=False)),
                ('is_stitching_done', models.BooleanField(default=False)),
                ('is_finishing_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
