# Generated by Django 5.2.15 on 2026-06-23 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jobcardrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Stitching'), ('P5', 'Job Work'), ('P6', 'Finishing Report'), ('P7', 'Person 7'), ('P8', 'Person 8'), ('P9', 'Person 9'), ('P10', 'Person 10'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.RenameModel('Person4Report', 'StitchingReport'),
        migrations.RenameModel('Person4ReportPhoto', 'StitchingReportPhoto'),
        migrations.RenameModel('Person5Report', 'JobWorkReport'),
        migrations.RenameModel('Person6Report', 'FinishingReport'),
        migrations.RenameModel('Person6ReportPhoto', 'FinishingReportPhoto'),
        migrations.RenameField(
            model_name='stitchingreportphoto',
            old_name='person4_report',
            new_name='stitching_report'
        ),
        migrations.RenameField(
            model_name='finishingreportphoto',
            old_name='person6_report',
            new_name='finishing_report'
        ),
        migrations.AlterField(
            model_name='stitchingreport',
            name='cutting_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stitching_reports', to='core.cuttingreport'),
        ),
        migrations.AlterField(
            model_name='jobworkreport',
            name='cutting_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobwork_reports', to='core.cuttingreport'),
        ),
        migrations.AlterField(
            model_name='finishingreport',
            name='cutting_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_reports', to='core.cuttingreport'),
        ),
        migrations.AlterModelOptions(
            name='stitchingreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stitching', 'verbose_name_plural': 'Stitching'},
        ),
        migrations.AlterModelOptions(
            name='jobworkreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Work', 'verbose_name_plural': 'Job Work'},
        ),
        migrations.AlterModelOptions(
            name='finishingreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Finishing Report', 'verbose_name_plural': 'Finishing Reports'},
        ),
    ]
