# Generated by Django 5.2.15 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_person4reportphoto_person4_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingreport',
            name='finishing_master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stitchingreport',
            name='stitching_master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MasterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Job Work', 'Job Work'), ('Finishing', 'Finishing')], max_length=50)),
            ],
            options={
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
