# Generated by Django 5.2.15 on 2026-06-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cuttingreport_master_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingreport',
            name='master_name',
        ),
        migrations.RemoveField(
            model_name='finishingreport',
            name='master_name',
        ),
        migrations.RemoveField(
            model_name='jobworkreport',
            name='master_name',
        ),
        migrations.RemoveField(
            model_name='stitchingreport',
            name='master_name',
        ),
    ]
