# Generated by Django 5.2.15 on 2026-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_cuttingreport_master_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finishingreport',
            name='master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobworkreport',
            name='master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stitchingreport',
            name='master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
