# Generated by Django 5.2.15 on 2026-06-24 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cuttingreport_master_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_embroidery_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_printing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_embroidery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastername',
            name='department',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Job Work', 'Job Work'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Stitching'), ('P5', 'Job Work'), ('P6', 'Finishing Report'), ('P7', 'Embroidery'), ('P8', 'Printing'), ('P9', 'Person 9'), ('P10', 'Person 10'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.CreateModel(
            name='EmbroideryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embroidery_worker', models.CharField(max_length=200)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('embroidery_type', models.CharField(choices=[('Embroidery In', 'Embroidery In'), ('Embroidery Out', 'Embroidery Out')], max_length=50)),
                ('purpose', models.CharField(max_length=300)),
                ('job_card_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('any_other_problem', models.TextField()),
                ('total_pcs_short', models.PositiveIntegerField()),
                ('total_pcs', models.PositiveIntegerField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embroidery_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Embroidery',
                'verbose_name_plural': 'Embroidery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_worker', models.CharField(max_length=200)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('printing_type', models.CharField(choices=[('Printing In', 'Printing In'), ('Printing Out', 'Printing Out')], max_length=50)),
                ('purpose', models.CharField(max_length=300)),
                ('job_card_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('any_other_problem', models.TextField()),
                ('total_pcs_short', models.PositiveIntegerField()),
                ('total_pcs', models.PositiveIntegerField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Printing',
                'verbose_name_plural': 'Printing',
                'ordering': ['-created_at'],
            },
        ),
    ]
