# Generated by Django 5.2.15 on 2026-06-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_jobcardrequirement_is_embroidery_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbroideryReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('embroidery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.embroideryreport')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('printing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.printingreport')),
            ],
        ),
    ]
