# Generated by Django 5.2.15 on 2026-06-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_embroideryreportphoto_printingreportphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_sewing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_singleneedle_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_sewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_singleneedle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastername',
            name='department',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Job Work', 'Job Work'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing'), ('Singleneedle', 'Singleneedle'), ('Sewing', 'Sewing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Stitching'), ('P5', 'Job Work'), ('P6', 'Finishing Report'), ('P7', 'Embroidery'), ('P8', 'Printing'), ('P9', 'Singleneedle'), ('P10', 'Sewing'), ('P11', 'Person 11'), ('P12', 'Person 12'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.CreateModel(
            name='SewingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sewing_master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_card_no', models.CharField(max_length=100)),
                ('line_in_date', models.DateField(blank=True, null=True)),
                ('total_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('line_out_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('darji_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('folding_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overlock_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('option_1', models.CharField(blank=True, max_length=200)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Sewing',
                'verbose_name_plural': 'Sewing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SewingReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sewing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.sewingreport')),
            ],
        ),
        migrations.CreateModel(
            name='SingleneedleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleneedle_master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_card_no', models.CharField(max_length=100)),
                ('line_in_date', models.DateField(blank=True, null=True)),
                ('total_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('line_out_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('darji_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('folding_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overlock_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('option_1', models.CharField(blank=True, max_length=200)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleneedle_reports', to='core.cuttingreport')),
            ],
            options={
                'verbose_name': 'Singleneedle',
                'verbose_name_plural': 'Singleneedle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleneedleReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('singleneedle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.singleneedlereport')),
            ],
        ),
    ]
