# Generated by Django 5.2.15 on 2026-06-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ratedefinition_sewingreport_rate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingreport',
            name='rate_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratedefinition'),
        ),
        migrations.AddField(
            model_name='cuttingreport',
            name='rate_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
