# Generated by Django 5.2.15 on 2026-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cuttingreport_rate_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embroideryreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='embroideryreport',
            name='embroidery_type',
        ),
        migrations.RemoveField(
            model_name='jobworkreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jobworkreport',
            name='job_work_type',
        ),
        migrations.RemoveField(
            model_name='printingreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='printingreport',
            name='printing_type',
        ),
        migrations.AddField(
            model_name='embroideryreport',
            name='embroidery_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embroideryreport',
            name='embroidery_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkreport',
            name='jobwork_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkreport',
            name='jobwork_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingreport',
            name='printing_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingreport',
            name='printing_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
