# Generated by Django 5.2.15 on 2026-06-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_embroideryreport_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.jobworkreport')),
            ],
        ),
    ]
