# Generated by Django 5.2.15 on 2026-07-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_jobworkreportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_embroidery_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_jobwork_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_printing_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
