# Generated by Django 5.2.15 on 2026-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_jobcardrequirement_in_progress_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_sewing_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_singleneedle_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_stitching_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
