# Generated by Django 5.2.15 on 2026-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_design_and_rates_to_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embroideryreport',
            name='rate_description',
        ),
        migrations.RemoveField(
            model_name='embroideryreport',
            name='rate_name',
        ),
        migrations.RemoveField(
            model_name='jobworkreport',
            name='rate_description',
        ),
        migrations.RemoveField(
            model_name='jobworkreport',
            name='rate_name',
        ),
        migrations.RemoveField(
            model_name='printingreport',
            name='rate_description',
        ),
        migrations.RemoveField(
            model_name='printingreport',
            name='rate_name',
        ),
    ]
