# Generated by Django 5.2.15 on 2026-07-04 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_rate_details_from_three_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingreport',
            name='rate_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratedefinition'),
        ),
        migrations.AddField(
            model_name='finishingreport',
            name='total_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
