# Generated by Django 5.2.15 on 2026-07-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_rates_to_finishing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mastername',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI ID / VPA'),
        ),
        migrations.CreateModel(
            name='MasterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI / NetBanking'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='UPI', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref No / UPI ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.mastername')),
            ],
            options={
                'verbose_name': 'Master Payment',
                'verbose_name_plural': 'Master Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
