# Generated by Django 5.2.15 on 2026-07-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_upi_and_masterpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterpayment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
