# Generated by Django 5.2.15 on 2026-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_masterpayment_end_date_masterpayment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_cutting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_embroidery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_finishing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_jobwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_printing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_sewing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_singleneedle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardrequirement',
            name='requires_stitching',
            field=models.IntegerField(default=0),
        ),
    ]
