# Generated by Django 5.2.15 on 2026-07-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_jobcardrequirement_requires_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=100, unique=True)),
                ('total_pcs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessories Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessoriesItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=150)),
                ('qty_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('', 'Not Set')], default='', max_length=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.accessoriesrecord')),
            ],
            options={
                'ordering': ['sr_no'],
                'unique_together': {('record', 'sr_no')},
            },
        ),
    ]
