# Generated by Django 5.2.15 on 2026-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_accessories_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriesitementry',
            name='status',
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='status_a',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='status_b',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='status_c',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='status_d',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('', 'Not Set')], default='', max_length=10),
        ),
    ]
