# Generated by Django 5.2.15 on 2026-07-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_accessory_custom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accessories_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.accessoriesrecord')),
            ],
        ),
    ]
