# Generated by Django 5.2.15 on 2026-07-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_accessoriesphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Master'), ('P1', 'Person 1 — Cutting Report'), ('P2', 'CR Lakshay'), ('P3', 'CR Rahul'), ('P4', 'Stitching'), ('P5', 'Job Work'), ('P6', 'Finishing Report'), ('P7', 'Embroidery'), ('P8', 'Printing'), ('P9', 'Singleneedle'), ('P10', 'Sewing'), ('P11', 'Job Work 1'), ('P12', 'Sewing 1'), ('P13', 'Person 13')], default='P1', max_length=10),
        ),
        migrations.CreateModel(
            name='MiscellaneousReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miscellaneous Report',
                'verbose_name_plural': 'Miscellaneous Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
                ('file_name', models.CharField(default='file', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.miscellaneousreport')),
            ],
        ),
    ]
