# Generated by Django 5.2.15 on 2026-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_misc_report_rename_p11_p12'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_jobwork1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_jobwork1_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_sewing1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='is_sewing1_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_jobwork1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcardrequirement',
            name='requires_sewing1',
            field=models.IntegerField(default=0),
        ),
    ]
