# Generated by Django 5.2.15 on 2026-07-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_jobwork1_sewing1_req_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastername',
            name='department',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Job Work', 'Job Work'), ('Job Work 1', 'Job Work 1'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing'), ('Singleneedle', 'Singleneedle'), ('Sewing', 'Sewing'), ('Sewing 1', 'Sewing 1')], max_length=50),
        ),
        migrations.CreateModel(
            name='JobWork1Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobworker', models.CharField(max_length=200)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose', models.CharField(max_length=300)),
                ('job_card_no', models.CharField(max_length=100)),
                ('jobwork_in', models.DateField(blank=True, null=True)),
                ('jobwork_out', models.DateField(blank=True, null=True)),
                ('any_other_problem', models.TextField()),
                ('total_pcs_short', models.PositiveIntegerField()),
                ('total_pcs', models.PositiveIntegerField()),
                ('design_jobwork', models.CharField(blank=True, max_length=200, null=True)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobwork1_reports', to='core.cuttingreport')),
                ('rate_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratedefinition')),
            ],
            options={
                'verbose_name': 'Job Work 1',
                'verbose_name_plural': 'Job Work 1',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobWork1ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_work1_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.jobwork1report')),
            ],
        ),
        migrations.CreateModel(
            name='Sewing1Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sewing_master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('master_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_card_no', models.CharField(max_length=100)),
                ('line_in_date', models.DateField(blank=True, null=True)),
                ('total_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('line_out_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('rate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rate_description', models.CharField(blank=True, max_length=300, null=True)),
                ('darji_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('folding_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('overlock_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('option_1', models.CharField(blank=True, max_length=200)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cutting_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing1_reports', to='core.cuttingreport')),
                ('rate_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ratedefinition')),
            ],
            options={
                'verbose_name': 'Sewing 1',
                'verbose_name_plural': 'Sewing 1',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sewing1ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_data', models.BinaryField()),
                ('photo_name', models.CharField(default='photo.jpg', max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sewing1_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.sewing1report')),
            ],
        ),
    ]
