# Generated by Django 5.2.15 on 2026-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_p11_p12_separate_report_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousreport',
            name='master_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='miscellaneousreport',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
