# Generated by Django 5.2.15 on 2026-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastername',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='article_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='article_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='article_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='article_d',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='vendor_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='vendor_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='vendor_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='vendor_d',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mastername',
            name='article',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accessoriesitementry',
            name='status_a',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='accessoriesitementry',
            name='status_b',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='accessoriesitementry',
            name='status_c',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='accessoriesitementry',
            name='status_d',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mastername',
            name='department',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Job Work', 'Job Work'), ('Job Work 1', 'Job Work 1'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing'), ('Singleneedle', 'Singleneedle'), ('Sewing', 'Sewing'), ('Sewing 1', 'Sewing 1'), ('Vendor', 'Vendor')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='mastername',
            unique_together={('name', 'department', 'article')},
        ),
    ]
