# Generated by Django 5.2.15 on 2026-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_mastername_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_content_type_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_content_type_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_content_type_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_content_type_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_data_a',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_data_b',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_data_c',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_data_d',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_name_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_name_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_name_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesitementry',
            name='photo_name_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
