# Generated by Django 5.2.15 on 2026-08-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_accessoriesitementry_photo_content_type_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linked_masters',
            field=models.ManyToManyField(blank=True, help_text='Link this user to multiple MasterName profiles they can view statements for.', related_name='linked_users', to='core.mastername'),
        ),
    ]
