# Generated by Django 5.2.15 on 2026-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_userprofile_linked_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='statement_password',
            field=models.CharField(blank=True, help_text='Password required for this user to view their ledger statement.', max_length=128, null=True),
        ),
    ]
