# Generated by Django 5.2.15 on 2026-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_userprofile_statement_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stores cleartext password for admin reference and reset dialog.', max_length=128, null=True),
        ),
    ]
