# Generated by Django 4.2.30 on 2026-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_slacktask_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastername',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastername',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
