# Generated by Django 4.2.30 on 2026-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_chatmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrecord',
            name='status_bar',
            field=models.CharField(blank=True, default='not_started', max_length=50),
        ),
    ]
