# Generated by Django 4.2.30 on 2026-08-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_accessoriesrecord_status_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrecord',
            name='status_bar_record',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
