# Generated by Django 4.2.30 on 2026-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_accessoriesrecord_status_bar_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrecord',
            name='record_not_started',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrecord',
            name='record_total_marked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrecord',
            name='record_total_ordered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrecord',
            name='record_total_received',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
