# Generated by Django 4.2.30 on 2026-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_accessoriesrecord_record_not_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_department',
            field=models.CharField(blank=True, help_text='Department for this user in Team Chat (used to show relevant masters in task assignment).', max_length=50, null=True),
        ),
    ]
