# Generated by Django 4.2.30 on 2026-09-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_chatmessage_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chat_department',
        ),
    ]
